version: '3.8'

services:
  app:
    build: .
    container_name: parknwash-api
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - REDIS_HOST=redis
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - mysql
      - redis
    networks:
      - parknwash-network

  mysql:
    image: mysql:8.0
    container_name: parknwash-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - parknwash-network

  redis:
    image: redis:7-alpine
    container_name: parknwash-redis
    restart: unless-stopped
    networks:
      - parknwash-network

volumes:
  mysql_data:

networks:
  parknwash-network:
    driver: bridge