version: '3.8'

services:
  app:
    image: webdevops/php-apache:7.4
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8090:80"          # change host port if needed
    environment:
      WEB_DOCUMENT_ROOT: /app/public   # serve Laravel from /public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DISPLAY_ERRORS: "0"
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 120
      # optional: PHP_DATE_TIMEZONE: Asia/Kuwait
    volumes:
      - ./:/app            # your repo (with vendor/) mounted into container
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache