version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: parknwash-api:latest
    container_name: parknwash-api
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - parknwash-network

networks:
  parknwash-network:
    driver: bridge